            - name: python-flake8
  # You may pin to the exact commit or the version.
  # uses: julianwachholz/flake8-action@75749239077651dfd0ecbe405899cdcb0673ee8f
  uses: julianwachholz/flake8-action@v2.0.2
  with:
    # The name of the check to add annotations to. Generally the same as the job that uses this action
    checkName: 
    # Path to use for flake8
    path: # optional, default is .
    # Package names of flake8 plugins passed on to the `pip install` command.
    plugins: # optional, default is 
    # Specify a config file for flake8
    config: # optional
    # Used for internal tests
    isTest: # optional, default is false
          


            - name: Run pytest
  # You may pin to the exact commit or the version.
  # uses: pavelzw/pytest-action@c9e5b9c8d93290ff47dcf6a28c6b19ca0b42e487
  uses: pavelzw/pytest-action@v2.1.0
  with:
    # Print a GitHub job summary
    job-summary: # optional, default is true
    # Verbose output
    verbose: # optional, default is true
    # Use emojis in the output
    emoji: # optional, default is true
    # Custom arguments to pass to pytest
    custom-arguments: # optional, default is 
    # Custom command to replace the `pytest` call. Can be a custom executable or something like `poetry run pytest` or `micromamba run -n myenv pytest`.
    custom-pytest: # optional, default is pytest
    # Title of the report
    report-title: # optional, default is Test Report
    # Add 'Click to expand' to the report
    click-to-expand: # optional, default is true
          
